// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutFeaturesSplit from '@/components/sections/about/AboutFeaturesSplit';
import { Award, CheckCircle, Shield, Sparkles, Star, Users } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutFeaturesSplit
          tag="Our Philosophy"
          title="Design that Reflects Your Essence"
          description="With over two decades of experience in the Madrid architecture and design scene, we specialize in curating bespoke interiors that tell your personal story through textures, light, and form."
          items={[
            {
              icon: Sparkles,
              title: "Bespoke Curation",
              description: "Every element is hand-selected to match your vision.",
            },
            {
              icon: CheckCircle,
              title: "Precision Execution",
              description: "From planning to installation, we manage every detail.",
            },
            {
              icon: Shield,
              title: "Quality Assurance",
              description: "We partner only with the finest local craftsmen.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/cropped-top-view-young-beautiful-female-architect-hands-doing-blueprints-with-ruler-pen-white-table-coworking-space-business-concept_176420-8525.jpg"
        />
        </SectionErrorBoundary>
      </div>
  );
}
