// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Get Started"
          text="Ready to transform your home in Madrid? Let's discuss your vision over a private consultation."
          primaryButton={{
            text: "Contact Us",
            href: "mailto:hello@studiomadrid.es",
          }}
          secondaryButton={{
            text: "Book a Tour",
            href: "#",
          }}
        />
        </SectionErrorBoundary>
      </div>
  );
}
