// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="Questions"
          title="Everything You Need to Know"
          description="Clear answers to start your design journey."
          categories={[
            {
              name: "Process",
              items: [
                {
                  question: "How long does a renovation take?",
                  answer: "Projects typically range from 2 to 6 months depending on scope.",
                },
                {
                  question: "Do you offer consultations?",
                  answer: "Yes, we provide initial site consultations to discuss your goals.",
                },
              ],
            },
            {
              name: "Services",
              items: [
                {
                  question: "Do you design commercial spaces?",
                  answer: "Our focus is primarily high-end residential interiors.",
                },
                {
                  question: "Do you source furniture?",
                  answer: "We manage sourcing, procurement, and installation as part of our service.",
                },
              ],
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
