// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesBentoGrid from '@/components/sections/features/FeaturesBentoGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesBentoGrid
          tag="Our Expertise"
          title="Comprehensive Design Services"
          description="End-to-end solutions tailored to your unique lifestyle."
          features={[
            {
              title: "Residential Design",
              description: "Full-scale home transformations and renovations.",
              imageSrc: "http://img.b2bpic.net/free-photo/modern-kitchen-surface-pull-out-drawer-loft-style-interior-design-details_169016-72762.jpg",
            },
            {
              title: "Space Optimization",
              description: "Maximizing functionality for urban Madrid flats.",
              imageSrc: "http://img.b2bpic.net/free-photo/young-woman-using-home-technology_23-2149216655.jpg",
            },
            {
              title: "Eco-Conscious Selection",
              description: "Sustainable sourcing for modern homes.",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-arrangement-modern-vases_23-2149646500.jpg",
            },
            {
              title: "Luxury Finishing",
              description: "Premium lighting, textures, and bespoke furniture.",
              imageSrc: "http://img.b2bpic.net/free-photo/lobby-living-room-hotel_1150-11124.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
