// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroCenteredLogos from '@/components/sections/hero/HeroCenteredLogos';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroCenteredLogos
          avatarsSrc={[
            "http://img.b2bpic.net/free-photo/young-people-having-fun_23-2149832986.jpg",
            "http://img.b2bpic.net/free-photo/family-moving-using-boxes_1157-35479.jpg",
            "http://img.b2bpic.net/free-photo/beautiful-young-african-american-woman-smiling-cheerful-friendly-face-laughing-confident_839833-29956.jpg",
            "http://img.b2bpic.net/free-photo/male-real-estate-agent-doing-business-showing-house-potential-buying-couple_23-2150164714.jpg",
            "http://img.b2bpic.net/free-photo/colleagues-sharing-high-five-office_482257-119313.jpg",
          ]}
          avatarText="Trusted by 500+ families"
          title="Crafting Timeless Spaces in the Heart of Madrid"
          description="We blend Mediterranean warmth with contemporary luxury to transform your home into a sanctuary of elegance and comfort."
          primaryButton={{
            text: "View Projects",
            href: "#projects",
          }}
          secondaryButton={{
            text: "Contact Us",
            href: "#contact",
          }}
          names={[
            "Madrid",
            "Barcelona",
            "Seville",
            "Valencia",
            "Bilbao",
            "Malaga",
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/close-up-happy-healthy-young-woman-with-dark-curly-hair-lying-comfortable-sofa-terrace_197531-22796.jpg"
        />
        </SectionErrorBoundary>
      </div>
  );
}
