// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsIconCards from '@/components/sections/metrics/MetricsIconCards';
import { Award, CheckCircle, Shield, Sparkles, Star, Users } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsIconCards
          tag="By the Numbers"
          title="A Track Record of Excellence"
          description="Results that speak for themselves."
          metrics={[
            {
              icon: Award,
              title: "Completed Projects",
              value: "350+",
            },
            {
              icon: Star,
              title: "Satisfied Clients",
              value: "500+",
            },
            {
              icon: Users,
              title: "Design Experts",
              value: "25+",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
