// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "projects" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProjectsSection(): React.JSX.Element {
  return (
    <div id="projects" data-section="projects">
        <SectionErrorBoundary name="projects">
              <FeaturesImageBento
          tag="Featured Work"
          title="Selected Projects in Madrid"
          description="Discover our latest transformations across the city."
          items={[
            {
              title: "Luxury Flat",
              description: "Barrio de Salamanca renovation",
              imageSrc: "http://img.b2bpic.net/free-photo/woman-reading-book-reading-club-library_23-2150293528.jpg",
            },
            {
              title: "Urban Oasis",
              description: "Modern terrace concept",
              imageSrc: "http://img.b2bpic.net/free-photo/modern-spacious-room-with-large-panoramic-window_7502-7289.jpg",
            },
            {
              title: "Boutique Villa",
              description: "Contemporary architecture",
              imageSrc: "http://img.b2bpic.net/free-photo/young-coworkers-gathering-table-office_23-2147668778.jpg",
            },
            {
              title: "Townhouse Staging",
              description: "Modern living transformation",
              imageSrc: "http://img.b2bpic.net/free-photo/side-view-blurry-man-walking_23-2150378941.jpg",
            },
            {
              title: "Minimalist Loft",
              description: "Open plan urban living",
              imageSrc: "http://img.b2bpic.net/free-photo/ai-generated-house-design_23-2150666254.jpg",
            },
            {
              title: "Traditional Fusion",
              description: "Renovating history",
              imageSrc: "http://img.b2bpic.net/free-photo/bathroom-interior-background-white-spa-towels-wood_1258-111485.jpg",
            },
            {
              title: "Private Residence",
              description: "Custom luxury detail",
              imageSrc: "http://img.b2bpic.net/free-photo/abstract-blur-furniture-shop-store-interior_74190-4976.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
