/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";
import { cls } from "@/lib/utils";

const items = [
  {
    title: "Luxury Flat",
    description: "Barrio de Salamanca penthouse",
    imageSrc: "http://img.b2bpic.net/free-photo/woman-reading-book-reading-club-library_23-2150293528.jpg",
    href: "/barrio-de-salamanca-penthouse"
  },
  {
    title: "Urban Oasis",
    description: "Modern terrace concept",
    imageSrc: "http://img.b2bpic.net/free-photo/modern-spacious-room-with-large-panoramic-window_7502-7289.jpg"
  },
  {
    title: "Boutique Villa",
    description: "Contemporary architecture",
    imageSrc: "http://img.b2bpic.net/free-photo/young-coworkers-gathering-table-office_23-2147668778.jpg"
  },
  {
    title: "Townhouse Staging",
    description: "Modern living transformation",
    imageSrc: "http://img.b2bpic.net/free-photo/side-view-blurry-man-walking_23-2150378941.jpg"
  },
  {
    title: "Minimalist Loft",
    description: "Open plan urban living",
    imageSrc: "http://img.b2bpic.net/free-photo/ai-generated-house-design_23-2150666254.jpg"
  },
  {
    title: "Traditional Fusion",
    description: "Renovating history",
    imageSrc: "http://img.b2bpic.net/free-photo/bathroom-interior-background-white-spa-towels-wood_1258-111485.jpg"
  },
  {
    title: "Private Residence",
    description: "Custom luxury detail",
    imageSrc: "http://img.b2bpic.net/free-photo/abstract-blur-furniture-shop-store-interior_74190-4976.jpg"
  }
];

type FeatureItem = {
  title: string;
  description: string;
  href?: string;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

interface FeaturesImageBentoProps {
  tag: string;
  title: string;
  description: string;
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  items: [FeatureItem, FeatureItem, FeatureItem, FeatureItem, FeatureItem, FeatureItem, FeatureItem];
}

const ProjectsInline = () => {
  const gridClasses = [
    "md:col-span-2",
    "md:col-span-4",
    "md:col-span-3",
    "md:col-span-3",
    "md:col-span-2",
    "md:col-span-2",
    "md:col-span-2",
  ];

  const staggerDelays = [
    0,
    0.1,
    0,
    0.1,
    0,
    0.1,
    0.2,
  ];

  return (
    <section aria-label="Features image bento section" className="py-20">
      <div className="flex flex-col gap-8 md:gap-10">
        <div className="flex flex-col items-center w-content-width mx-auto gap-2">
          <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
            <p>{"Featured Work"}</p>
          </div>

          <TextAnimation
            text={"Selected Projects in Madrid"}
            variant="fade-blur"
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"Discover our latest transformations across the city."}
            variant="fade-blur"
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
          />

          {(undefined || undefined) && (
            <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
              {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
              {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary" animationDelay={0.1} />}
            </div>
          )}
        </div>

        <div className="w-content-width mx-auto grid grid-cols-1 md:grid-cols-6 gap-3">
          {items.map((item, index) => {
            const content = (
              <div className="relative h-80 xl:h-100 2xl:h-120 overflow-hidden">
                <ImageOrVideo
                  imageSrc={item.imageSrc}
                  videoSrc={item.videoSrc}
                  className="rounded group-hover:scale-105 transition-transform duration-500"
                />

                <div className="absolute inset-x-5 bottom-5 xl:inset-x-6 xl:bottom-6 2xl:inset-x-7 2xl:bottom-7 flex flex-col text-background">
                  <span className="text-2xl font-semibold leading-snug truncate">{item.title}</span>
                  <span className="text-base leading-snug truncate">{item.description}</span>
                </div>
              </div>
            );

            return (
              <ScrollReveal key={index} variant="fade" delay={staggerDelays[index]} className={cls("col-span-1 group", gridClasses[index])}>
                {item.href ? (
                  <a href={item.href} className="block overflow-hidden rounded">
                    {content}
                  </a>
                ) : (
                  <div className="overflow-hidden rounded">
                    {content}
                  </div>
                )}
              </ScrollReveal>
            );
          })}
        </div>
      </div>
    </section>
  );
};

export default function ProjectsSection() {
  return (
    <div data-webild-section="projects" id="projects">
      <ProjectsInline />
    </div>
  );
}
